4. times do
  synth :beep, amp: 1
  synth :blade, amp: 0
  synth :bnoise, amp: 0
  synth :chipbass, amp: 0
  synth :chiplead, amp: 0
  synth :chipnoise, amp: 0
  synth :cnoise, amp: 0
  synth :dark_ambience, amp: 0
  synth :dpulse, amp: 0
  synth :dsaw, amp: 0
  synth :dtri, amp: 0
  synth :dull_bell, amp: 0
  synth :fm, amp: 0
  synth :gnoise, amp: 0
  synth :growl, amp: 0
  synth :hollow, amp: 0
  synth :hoover, amp: 0
  synth :mod_beep, amp: 0
  synth :mod_dsaw, amp: 0
  synth :mod_fm, amp: 0
  synth :mod_pulse, amp: 0
  synth :mod_saw, amp: 0
  synth :mod_sine, amp: 0
  synth :mod_tri, amp: 0
  synth :noise, amp: 0
  synth :piano, amp: 0
  synth :pluck, amp: 0
  synth :pnoise, amp: 0
  synth :pretty_bell, amp: 0
  synth :prophet, amp: 0
  synth :pulse, amp: 0
  synth :saw, amp: 0
  synth :sine, amp: 0
  synth :sound_in, amp: 0
  synth :sound_in_stereo, amp: 0
  synth :square, amp: 0
  synth :subpulse, amp: 0
  synth :supersaw, amp: 0
  synth :tb303, amp: 0
  synth :tech_saws, amp: 0
  synth :tri, amp: 0
  synth :zawa, amp: 0
  sleep 0.5
end
